os:
  - linux
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node
    - node_modules
env:
  global:
    - GB_BASE=$TRAVIS_BUILD_DIR
before_install:
  - export TZ=Europe/Amsterdam
  - date
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
  - ng build
script:
  - ng test --single-run 
notifications:
  webhooks:
    on_success: change
    on_failure: always
on_start: false

