os:
  - linux
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node
    - node_modules
env:
  global:
    - GB_BASE=$TRAVIS_BUILD_DIR
before_install:
  - node -v
  - export TZ=Europe/Amsterdam
  - date
install:
  - npm install
  - ng build
script:
  - ng build -prod
notifications:
  webhooks:
    on_success: change
    on_failure: always
on_start: false

