#codecov:
#  notify:
#    require_ci_to_pass: yes
#
#comment:
#  layout: "header, diff, changes, flags, files"
#  behavior: default
#  require_changes: false  # if true: only post the comment if coverage changes
#  require_base: no        # [yes :: must have a base report to post]
#  require_head: yes       # [yes :: must have a head report to post]
#  branches: null
#
#coverage:
#  precision: 2
#  round: down
#  range: "50...90"
#
#  status:
#    project:
#      default:
#        target: auto
#        threshold: null
#        base: auto
#    patch:
#      default:
#        target: auto
#        threshold: null
#        base: auto
#        if_not_found: success

