version: '3.4'

services:

  gb-nginx:
    image: medco/glowing-bear:latest
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
      target: prod
    ports:
      - "82:80"
    environment:
      - GB_API_URL=http://iccluster046.iccluster.epfl.ch:8082/IRCT-CL/rest
      - GB_URL=http://iccluster046.iccluster.epfl.ch:82
      - GB_OIDC_URL=http://iccluster046.iccluster.epfl.ch:8081/auth/realms/master/protocol/openid-connect
      - GB_OIDC_CLIENT_ID=i2b2
      - GB_PICSURE_RES_NAME=i2b2-medco-icclusters
      - GB_GENOMIC_ANNOTATIONS_URL=http://iccluster046.iccluster.epfl.ch/php
