version: '3.5'

services:
  dev-server:
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
      target: dev
    ports:
      - "4200:4200"
    volumes:
      - ..:/glowing-bear-src

  glowing-bear:
    image: medco/glowing-bear:dev
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
      target: release
    ports:
      - "82:80"
    environment:
      - GB_API_URL=http://pic-sure.localhost/IRCT-CL/rest
      - GB_URL=http://localhost:81
      - GB_OIDC_URL=http://keycloak.localhost/auth/realms/master/protocol/openid-connect
      - GB_OIDC_CLIENT_ID=i2b2-local
      - GB_PICSURE_RES_NAME=i2b2-medco-local
      - GB_COTHORITY_KEY_URL=http://localhost/cothority-key.pub.toml
      - GB_GENOMIC_ANNOTATIONS_URL=http://localhost/genomicAnnotations
      - GB_MEDCO_RESULTS_RANDOMIZATION=0
      - GB_FOOTER_TEXT=
