version: '3.5'

services:
  dev-server:
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
      target: dev
    ports:
      - "4200:4200"
    volumes:
      - ..:/glowing-bear-src

  glowing-bear-medco:
    image: medco/glowing-bear-medco:dev
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
      target: release
    ports:
      - "82:80"
    environment:
      - GB_API_URL=http://localhost/pic-sure-api-2/PICSURE
      - GB_URL=http://localhost/glowing-bear
      - GB_OIDC_URL=http://localhost/auth/realms/master/protocol/openid-connect
      - GB_OIDC_CLIENT_ID=medco
      - GB_COTHORITY_KEY_URL=http://localhost/cothority-key.pub.toml
      - GB_GENOMIC_ANNOTATIONS_URL=http://localhost/genomicAnnotations
      - GB_MEDCO_RESULTS_RANDOMIZATION=0
      - GB_FOOTER_TEXT=
      - MEDCO_NETWORK_NAME=testnetwork
      - MEDCO_NODES_NAME=a,b,c

  gen-mapping-table:
    image: medco/medco-unlynx:latest
    user: ${USER_ID:?}
    command: ["m", "--outputFile", "/output/point-to-int-mapping.ts", "--outputFormat", "typescript",
              "--nbMappings", "1000", "--checkNeg", "false"]
    volumes:
      - ../src/app/utilities/crypto:/output
