version: "3.5"

services:
  dev-server:
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
      target: dev
    ports:
      - "4300:4200"
    volumes:
      - ..:/glowing-bear-src
    user: ${USER_GROUP:?}

  glowing-bear-medco:
    image: medco/glowing-bear-medco:dev
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
      target: release
    ports:
      - "82:80"
    environment:
      - GB_MEDCO_NODE_URL=http://localhost:3001
      - GB_KEYCLOAK_URL=http://localhost:8080/auth
      - GB_KEYCLOAK_REALM=ti-realm
      - GB_KEYCLOAK_CLIENT_ID=glowing-bear
      - GB_FOOTER_TEXT=
