version: '3.5'

services:
  dev-server:
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
      target: dev
    ports:
      - "4200:4200"
    volumes:
      - ..:/glowing-bear-src
    user: ${USER_GROUP:?}

  glowing-bear-medco:
    image: medco/glowing-bear-medco:dev
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
      target: release
    ports:
      - "82:80"
    environment:
      - GB_MEDCO_NODE_URL=http://localhost/local-3nodes/medco-0
      - GB_KEYCLOAK_URL=http://localhost/auth
      - GB_KEYCLOAK_REALM=master
      - GB_KEYCLOAK_CLIENT_ID=medco
      - GB_FOOTER_TEXT=
