name: CI
on:
  push:
  pull_request:

jobs:
  npm-tests:
    name: Code beautification and unit tests
    runs-on: ubuntu-latest
    env:
      TI_ACCESS_TOKEN: ${{ secrets.TI_ACCESS_TOKEN }}

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: node --version

      - name: Environment
        run: |
          go version
          npm version
          env

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install NPM dependencies
        run: npm install --force

      - name: Run linter
        run: npm run lint

      - name: Run unit tests
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
        env:
          CI: true
